### ISSUE TITLE
Virus???

### ISSUE THREAD

**Issue by imtrynalearn** [kalari123/Growtopia-Gabb#1]
https://www.virustotal.com/gui/file/5903c174258e00e1c52d1f96f41b940a78fdf102dc2b3b62c01e55bf1257093d/detection

**Comment by kalari123** [comment]
> https://www.virustotal.com/gui/file/5903c174258e00e1c52d1f96f41b940a78fdf102dc2b3b62c01e55bf1257093d/detection

Detected as virus cuz obfuscated
